
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: #
      POSTGRES_USER: #
      POSTGRES_PASSWORD: #
  

  redis:
    image: "redis:alpine"