# Generated by Django 5.1.2 on 2024-11-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientselection',
            name='selected_items',
            field=models.JSONField(default=list),
        ),
    ]
