# Generated by Django 5.1.2 on 2024-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_pendinguser_delete_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
